# Generated by Django 4.1.2 on 2022-10-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentaudio',
            name='counter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contentaudio',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='counter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contentvideo',
            name='counter',
            field=models.IntegerField(),
        ),
    ]
