# Generated by Django 4.1.2 on 2022-10-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_contentaudio_counter_alter_contentaudio_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentvideo',
            name='order',
            field=models.IntegerField(),
        ),
    ]
