# Generated by Django 4.1.2 on 2022-10-10 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_contentaudio_counter_remove_contentaudio_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentaudio',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
        migrations.AlterField(
            model_name='contentvideo',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
    ]
