# Generated by Django 4.1.2 on 2022-10-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_contentaudio_options_alter_contenttext_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentaudio',
            name='bitrate',
            field=models.IntegerField(verbose_name='Битрейт'),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contentvideo',
            name='url_file',
            field=models.URLField(verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='contentvideo',
            name='url_sub',
            field=models.URLField(verbose_name='Ссылка на субтитры'),
        ),
    ]
