# Generated by Django 4.1.2 on 2022-10-11 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_contentaudio_bitrate_alter_contenttext_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentaudio',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_audio', to='cms.page', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='contenttext',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_text', to='cms.page', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contentvideo',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_video', to='cms.page', verbose_name='Видео'),
        ),
    ]
